routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('welcome');
});

Route::resource('candidates', 'CandidatesController')->middleware('auth');
Route::resource('interviews', 'IntreviewController')->middleware('auth');
Route::get('candidates/delete/{id}', 'CandidatesController@destroy')->name('candidate.delete');

Route::get('candidates/changeuser/{cid}/{uid?}', 'CandidatesController@changeUser')->name('candidate.changeuser');

Route::get('candidates/changestatus/{cid}/{sid}', 'CandidatesController@changeStatus')->name('candidate.changestatus');
Route::get('/mycandidates', 'CandidatesController@mycandidates')->name('candidates.mycandidates')->middleware('auth');
Route::get('/myinterviews', 'IntreviewController@myinterviews')->name('interviews.myinterviews')->middleware('auth');

Route::get('/hello', function(){
    return 'Hello Laravel';
});

Route::get('/student/{id}', function($id = 'No Student found'){
    return 'We got student with id '.$id;
});

Route::get('/car/{id?}', function($id = null){
    if(isset($id)){
        //TODO: validate for integer
        return "We got car $id";
    }
    else{
        return 'We need the id to find your car';
    }
});
Route::get('/comment/{id}', function ($id) {
    return view('comment', compact('id'));
});


Route::get('/users/{name}/{email?}', function ($name,$email= 'email missing') {
    return view('users', compact('name','email'));
});



Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/interviews/create.blade.php
@extends('layouts.app')

@section('title','Create Interview')

@section('content')
    <body>
        <h1>create Interview</h1>
        <form method = "post" action = "{{action('IntreviewController@store')}}">
            @csrf
            <div class="form-group" >
                <label for = "date">Interview date</label>
                <input type = "date" class="form-control" name = "date">
            </div>
            <div class="form-group" >
                <label for = "name">Interview summary</label>
                <input type = "text" class="form-control" name = "summary">
            </div>

            <div class="form-group">
                <label for="candidate_id" class="col-md-4 control-label text-md-right">Candidate</label>
                <div class="col-md-6">
                    <select class="form-control" name="candidate_id">
                        <option value="" disabled selected hidden>Choose Candidate</option>
                        @foreach($candidates as $candidate)
                        <option value="{{ $candidate->id }}">{{ $candidate->name }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label for="user_id" class="col-md-4 control-label text-md-right">Interviewer</label>
                    <div class="col-md-6">
                        <select class="form-control" name="user_id">
                            <option value="" disabled selected hidden>{{Illuminate\Support\Facades\Auth::user()->name}}</option>

                            @foreach($users as $user)
                            <option value="{{ $user->id }}">{{ $user->name }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <input type = "submit" class="form-control" name = "submit" value = "Create Interview">
                    </div>
            @if ($errors->any())
            <div class="alert alert-danger">
            <ul>
              @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
             @endforeach
            </ul>
            </div>
        @endif
        </form>
    </body>
@endsection

resources/views/interviews/index.blade.php
@extends('layouts.app')

@section('title','Interviews')

@section('content')

@if(Session::has('notallowed'))
<div class='alert alert-danger'>
    {{Session::get('notallowed')}}
</div>

@endif

         @if (Session::has('message'))
            <div class="alert alert-success">{{Session::get('message')}} </div>
        @endif
    <div><a class="badge badge-primary text-wrap" href="{{route('interviews.create')}}">Add new Interview</a></div>

    <h1> List of Interviews</h1>
    <table class="table table-dark">
            <tr>
                <th>id</th><th>Date</th><th>Summary</th><th>Candidates</th><th>Interviewer</th><th>Created</th><th>Updated</th>
            </tr>
        <!-- the table data -->
            @foreach($interviews as $interview)
            <tr>
            <td> {{$interview->id}}</td>
            <td> {{$interview->date}}</td>
            <td> {{$interview->summary}}</td>
            <td> {{$interview->candidateInter->name}}
            <td> {{$interview->userInter->name}}
            <td> {{$interview->created_at}}</td>
            <td> {{$interview->updated_at}}</td>

        </tr>
            @endforeach
    </table>
@endsection